CREATE USER c##dev IDENTIFIED BY pass;
GRANT CREATE SESSION TO c##dev ;
GRANT CREATE TABLESPACE TO c##dev ;
GRANT UNLIMITED TABLESPACE TO c##dev;

CREATE USER c##prod IDENTIFIED BY pass;
GRANT CREATE SESSION TO c##prod;

SELECT * FROM all_tables;
SELECT * FROM all_procedures;